---
openapi: 3.0.2
info:
  title: Case Management
  version: 1.0.0
  description: API to allow Fraud Analyst to evaluate real-time policy breach and
    fraud
  contact:
    name: Peregrine Software Architecture Team
    url: https://peregrine.com
    email: software.architecture@peregrine.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: http://dev.peregrine.com/api
  description: Development server for APIs test
- url: http://peregrine.com/api
  description: Production APIs server
paths:
  /cases:
    summary: Manage possible fraud and policy breach cases
    description: Manage possible fraud and policy breach cases
    get:
      parameters:
      - examples:
          top:
            value: "98"
        name: top
        description: 'Restrict number of cases. Min 1 and max 100. Default is set
          to max '
        schema:
          type: integer
        in: query
      - examples:
          skip:
            value: "25"
        name: skip
        description: Offset in the driver records list
        schema:
          type: integer
        in: query
      - examples:
          'single case type ':
            value: '"alternativeDriver"'
          multiple case type:
            value: "\"personalDetails, alternativeDriver\""
        name: type
        description: Filter by case type
        schema:
          enum:
          - alternativeDriver
          - learnerInMotorway
          - personalDetails
          type: string
        in: query
      - examples:
          driver identifier:
            value: '"B944AEA7-C8C7-4C64-B9D9-195E055E8F6F"'
        name: driver
        description: Get cases by specific driver
        schema:
          type: string
        in: query
      - examples:
          start date:
            value: '"2018-02-10T09:30Z"'
        name: startDate
        description: Filter cases from the parameter value date
        schema:
          format: date-time
          type: string
        in: query
      - examples:
          end date:
            value: '"2018-02-10T09:30Z"'
        name: endDate
        description: Filter driver trips to the parameter value date
        schema:
          format: date-time
          type: string
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
              examples:
                list of cases:
                  value:
                  - identifier: A91A69AD-DE28-429B-B187-2B5AD8E083EE
                    driver:
                      name: Felipe Rodrigues
                      identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
                      dateOfBirth: 2018-01-17
                      maritalStatus: married
                      job:
                        title: Software Engineer
                        startDate: 2019-03-24
                        companyName: Microsoft
                        companyAddress1: "South County Business Park, One Microsoft\
                          \ Place"
                        companyAddress2: Carmanhall and Leopardstown
                        companyCity: Dublin
                        companyEircode: D18 P521
                        companyGeoLocation: "53.2695466463407, -6.196220861370553"
                      mobileNumber: +353892077323
                      socialMedias:
                      - socialMedia: Instagram
                        url: https://www.instagram.com/felipepachecor/
                        activities:
                        - type: comment
                          content: some text
                          date: 2018-02-10T09:30Z
                          url: https://www.instagram.com/felipepachecor/commentIdentfier
                        - type: checkin
                          content: "53.2734,-7.77832031"
                          date: 2018-02-10T09:30Z
                      - socialMedia: Facebook
                        url: https://www.facebook.com/pachecorodriguesfelipe
                        activities:
                        - type: comment
                          content: some text
                          date: 2018-02-10T09:30Z
                          url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
                      trips:
                      - startDate: 2018-02-10T09:30Z
                        endDate: 2018-02-10T09:30Z
                        distance: 6.07
                        numberOfOverSpeeding: 1
                        numberOfAcceleration: 2
                        numberOfDeceleration: 0
                        numberOfMobileUsage: 3
                        riskScore: 2
                        identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
                        route:
                          type: FeatureCollection
                          features:
                          - type: Feature
                            properties: {}
                            geometry:
                              type: LineString
                              coordinates:
                              - - -44.91339683532715
                                - -20.145158581773966
                              - - -44.92348194122314
                                - -20.1452794514767
                        mobile: +353892077323
                      - startDate: 2018-02-10T09:30Z
                        endDate: 2018-02-10T09:30Z
                        distance: 5.73
                        numberOfOverSpeeding: 4
                        numberOfAcceleration: 3
                        numberOfDeceleration: 2
                        numberOfMobileUsage: 3
                        riskScore: 5
                        identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
                        route:
                          type: FeatureCollection
                          features:
                          - type: Feature
                            properties: {}
                            geometry:
                              type: LineString
                              coordinates:
                              - - -44.90743160247803
                                - -20.16574537177958
                              - - -44.89957809448242
                                - -20.144272201095905
                        mobile: +353892077323
                      licence:
                        type: LearnerPermit
                        issueDate: 2018-01-17
                        class: B
                        number: ASD123FGH
                        totalPenalties: 0
                      employmentType: FullTime
                      cars:
                      - maker: Audi
                        model: A4
                        year: 2017
                        registration: 172L1234
                        value: 15000
                    comment: "Possible driver that holds learner permit driving in\
                      \ motorways, e.g. trip identfier: XXX"
                    createDate: 2021-02-10T09:30Z
                    type: learnerInMotorway
                    probabilityScore: 0.45
                  - identifier: B61A69AD-DE28-429B-B187-2B5AD8E083AA
                    driver:
                      name: Steve Jobs
                      identifier: C61A69AD-DE28-429B-B187-2B5AD8E083ZZ
                      dateOfBirth: 1985-12-17
                      maritalStatus: divorced
                      job:
                        title: Software Engineer
                        startDate: 2018-01-17
                        companyName: Apple
                        companyAddress1: 1 Apple Place
                        companyCity: Apple City
                      mobileNumber: +35387547658
                      socialMedias:
                      - socialMedia: Linkedin
                        url: some text
                        activities:
                        - type: post
                          content: some text
                          date: 2021-02-10T09:30Z
                          url: some text
                        - type: comment
                          content: some text
                          date: 2018-02-10T09:30Z
                          url: some text
                      - socialMedia: Instagram
                        url: some text
                        activities:
                        - type: checkin
                          content: some text
                          date: 2021-02-10T09:30Z
                          url: some text
                        - type: post
                          content: some text
                          date: 2021-02-10T09:30Z
                          url: some text
                      trips:
                      - startDate: 2021-02-10T09:30Z
                        endDate: 2021-02-10T09:30Z
                        distance: 10
                        numberOfOverSpeeding: 0
                        numberOfAcceleration: 0
                        numberOfDeceleration: 0
                        numberOfMobileUsage: 0
                        riskScore: 1
                        identifier: 997AA36D-5F92-411F-9B58-51260FDAC8BA
                        route: some text
                        mobile: some text
                      - startDate: 2021-02-10T09:30Z
                        endDate: 2021-02-10T09:30Z
                        distance: 34
                        numberOfOverSpeeding: 1
                        numberOfAcceleration: 2
                        numberOfDeceleration: 1
                        numberOfMobileUsage: 2
                        riskScore: 2
                        identifier: some text
                        route: some text
                        mobile: some text
                      licence:
                        type: FullPermit
                        issueDate: 2018-01-17
                        class: B
                        number: some text
                        totalPenalties: 1
                      employmentType: Employed
                      cars:
                      - maker: Fiat
                        model: Punto
                        year: 2014
                        registration: 142D456
                        value: 64.1
                    comment: some text
                    createDate: 2018-02-10T09:30Z
                    type: learnerInMotorway
                    probabilityScore: 0.94
          description: Success operation
        "500":
          description: "Error trying to retrieve data from server, try again later"
      summary: Get cases
      description: Get cases details
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Case'
            examples:
              list of cases:
                value:
                - identifier: A91A69AD-DE28-429B-B187-2B5AD8E083EE
                  driver:
                    name: Felipe Rodrigues
                    identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
                    dateOfBirth: 2018-01-17
                    maritalStatus: married
                    job:
                      title: Software Engineer
                      startDate: 2019-03-24
                      companyName: Microsoft
                      companyAddress1: "South County Business Park, One Microsoft\
                        \ Place"
                      companyAddress2: Carmanhall and Leopardstown
                      companyCity: Dublin
                      companyEircode: D18 P521
                      companyGeoLocation: "53.2695466463407, -6.196220861370553"
                    mobileNumber: +353892077323
                    socialMedias:
                    - socialMedia: Instagram
                      url: https://www.instagram.com/felipepachecor/
                      activities:
                      - type: comment
                        content: some text
                        date: 2018-02-10T09:30Z
                        url: https://www.instagram.com/felipepachecor/commentIdentfier
                      - type: checkin
                        content: "53.2734,-7.77832031"
                        date: 2018-02-10T09:30Z
                    - socialMedia: Facebook
                      url: https://www.facebook.com/pachecorodriguesfelipe
                      activities:
                      - type: comment
                        content: some text
                        date: 2018-02-10T09:30Z
                        url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
                    trips:
                    - startDate: 2018-02-10T09:30Z
                      endDate: 2018-02-10T09:30Z
                      distance: 6.07
                      numberOfOverSpeeding: 1
                      numberOfAcceleration: 2
                      numberOfDeceleration: 0
                      numberOfMobileUsage: 3
                      riskScore: 2
                      identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
                      route:
                        type: FeatureCollection
                        features:
                        - type: Feature
                          properties: {}
                          geometry:
                            type: LineString
                            coordinates:
                            - - -44.91339683532715
                              - -20.145158581773966
                            - - -44.92348194122314
                              - -20.1452794514767
                      mobile: +353892077323
                    - startDate: 2018-02-10T09:30Z
                      endDate: 2018-02-10T09:30Z
                      distance: 5.73
                      numberOfOverSpeeding: 4
                      numberOfAcceleration: 3
                      numberOfDeceleration: 2
                      numberOfMobileUsage: 3
                      riskScore: 5
                      identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
                      route:
                        type: FeatureCollection
                        features:
                        - type: Feature
                          properties: {}
                          geometry:
                            type: LineString
                            coordinates:
                            - - -44.90743160247803
                              - -20.16574537177958
                            - - -44.89957809448242
                              - -20.144272201095905
                      mobile: +353892077323
                    licence:
                      type: LearnerPermit
                      issueDate: 2018-01-17
                      class: B
                      number: ASD123FGH
                      totalPenalties: 0
                    employmentType: FullTime
                    cars:
                    - maker: Audi
                      model: A4
                      year: 2017
                      registration: 172L1234
                      value: 15000
                  comment: Possible driver that holds learner permit driving in motorways
                  createDate: 2021-02-10T09:30Z
                  type: learnerInMotorway
                  probabilityScore: 0.65
        required: true
      responses:
        "201":
          description: Success operation
        "400":
          description: Invalid payload
      summary: Create case
      description: |
        Create cases
  /cases/{identifier}:
    summary: Manage single possible fraud and policy breach cases
    description: Manage single possible fraud and policy breach cases
    get:
      parameters:
      - examples:
          case identifier:
            value: '"7F9DDDBB-9D02-4FD9-8B65-210A793E139B"'
        name: identifier
        description: Case identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
              examples:
                single case:
                  value:
                    identifier: A91A69AD-DE28-429B-B187-2B5AD8E083EE
                    driver:
                      name: Felipe Rodrigues
                      identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
                      dateOfBirth: 2018-01-17
                      maritalStatus: married
                      job:
                        title: Software Engineer
                        startDate: 2019-03-24
                        companyName: Microsoft
                        companyAddress1: "South County Business Park, One Microsoft\
                          \ Place"
                        companyAddress2: Carmanhall and Leopardstown
                        companyCity: Dublin
                        companyEircode: D18 P521
                        companyGeoLocation: "53.2695466463407, -6.196220861370553"
                      mobileNumber: +353892077323
                      socialMedias:
                      - socialMedia: Instagram
                        url: https://www.instagram.com/felipepachecor/
                        activities:
                        - type: comment
                          content: some text
                          date: 2018-02-10T09:30Z
                          url: https://www.instagram.com/felipepachecor/commentIdentfier
                        - type: checkin
                          content: "53.2734,-7.77832031"
                          date: 2018-02-10T09:30Z
                      - socialMedia: Facebook
                        url: https://www.facebook.com/pachecorodriguesfelipe
                        activities:
                        - type: comment
                          content: some text
                          date: 2018-02-10T09:30Z
                          url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
                      trips:
                      - startDate: 2018-02-10T09:30Z
                        endDate: 2018-02-10T09:30Z
                        distance: 6.07
                        numberOfOverSpeeding: 1
                        numberOfAcceleration: 2
                        numberOfDeceleration: 0
                        numberOfMobileUsage: 3
                        riskScore: 2
                        identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
                        route:
                          type: FeatureCollection
                          features:
                          - type: Feature
                            properties: {}
                            geometry:
                              type: LineString
                              coordinates:
                              - - -44.91339683532715
                                - -20.145158581773966
                              - - -44.92348194122314
                                - -20.1452794514767
                        mobile: +353892077323
                      - startDate: 2018-02-10T09:30Z
                        endDate: 2018-02-10T09:30Z
                        distance: 5.73
                        numberOfOverSpeeding: 4
                        numberOfAcceleration: 3
                        numberOfDeceleration: 2
                        numberOfMobileUsage: 3
                        riskScore: 5
                        identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
                        route:
                          type: FeatureCollection
                          features:
                          - type: Feature
                            properties: {}
                            geometry:
                              type: LineString
                              coordinates:
                              - - -44.90743160247803
                                - -20.16574537177958
                              - - -44.89957809448242
                                - -20.144272201095905
                        mobile: +353892077323
                      licence:
                        type: LearnerPermit
                        issueDate: 2018-01-17
                        class: B
                        number: ASD123FGH
                        totalPenalties: 0
                      employmentType: FullTime
                      cars:
                      - maker: Audi
                        model: A4
                        year: 2017
                        registration: 172L1234
                        value: 15000
                    comment: Possible driver that holds learner permit driving in
                      motorways
                    createDate: 2021-02-10T09:30Z
                    type: learnerInMotorway
                    probabilityScore: 0.34
          description: Success operation
      summary: Get case
      description: Get single case
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Case'
            examples:
              single case:
                value:
                  identifier: A91A69AD-DE28-429B-B187-2B5AD8E083EE
                  driver:
                    name: Felipe Rodrigues
                    identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
                    dateOfBirth: 2018-01-17
                    maritalStatus: married
                    job:
                      title: Software Engineer
                      startDate: 2019-03-24
                      companyName: Microsoft
                      companyAddress1: "South County Business Park, One Microsoft\
                        \ Place"
                      companyAddress2: Carmanhall and Leopardstown
                      companyCity: Dublin
                      companyEircode: D18 P521
                      companyGeoLocation: "53.2695466463407, -6.196220861370553"
                    mobileNumber: +353892077323
                    socialMedias:
                    - socialMedia: Instagram
                      url: https://www.instagram.com/felipepachecor/
                      activities:
                      - type: comment
                        content: some text
                        date: 2018-02-10T09:30Z
                        url: https://www.instagram.com/felipepachecor/commentIdentfier
                      - type: checkin
                        content: "53.2734,-7.77832031"
                        date: 2018-02-10T09:30Z
                    - socialMedia: Facebook
                      url: https://www.facebook.com/pachecorodriguesfelipe
                      activities:
                      - type: comment
                        content: some text
                        date: 2018-02-10T09:30Z
                        url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
                    trips:
                    - startDate: 2018-02-10T09:30Z
                      endDate: 2018-02-10T09:30Z
                      distance: 6.07
                      numberOfOverSpeeding: 1
                      numberOfAcceleration: 2
                      numberOfDeceleration: 0
                      numberOfMobileUsage: 3
                      riskScore: 2
                      identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
                      route:
                        type: FeatureCollection
                        features:
                        - type: Feature
                          properties: {}
                          geometry:
                            type: LineString
                            coordinates:
                            - - -44.91339683532715
                              - -20.145158581773966
                            - - -44.92348194122314
                              - -20.1452794514767
                      mobile: +353892077323
                    - startDate: 2018-02-10T09:30Z
                      endDate: 2018-02-10T09:30Z
                      distance: 5.73
                      numberOfOverSpeeding: 4
                      numberOfAcceleration: 3
                      numberOfDeceleration: 2
                      numberOfMobileUsage: 3
                      riskScore: 5
                      identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
                      route:
                        type: FeatureCollection
                        features:
                        - type: Feature
                          properties: {}
                          geometry:
                            type: LineString
                            coordinates:
                            - - -44.90743160247803
                              - -20.16574537177958
                            - - -44.89957809448242
                              - -20.144272201095905
                      mobile: +353892077323
                    licence:
                      type: LearnerPermit
                      issueDate: 2018-01-17
                      class: B
                      number: ASD123FGH
                      totalPenalties: 0
                    employmentType: FullTime
                    cars:
                    - maker: Audi
                      model: A4
                      year: 2017
                      registration: 172L1234
                      value: 15000
                  comment: Possible driver that holds learner permit driving in motorways
                  createDate: 2021-02-10T09:30Z
                  type: learnerInMotorway
                  probabilityScore: 0.12
        required: true
      parameters:
      - examples:
          case identifier:
            value: '"7F9DDDBB-9D02-4FD9-8B65-210A793E139B"'
        name: identifier
        description: Case identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Case not found
      summary: Update case
      description: Update case details
    delete:
      parameters:
      - examples:
          case identifier:
            value: '"7F9DDDBB-9D02-4FD9-8B65-210A793E139B"'
        name: identifier
        description: Case identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Case not found
        "401":
          description: Unauthorized resource
      summary: Delete case
      description: Delete case
    parameters:
    - examples:
        case identifier:
          value: '"7F9DDDBB-9D02-4FD9-8B65-210A793E139B"'
      name: identifier
      description: Case identifier
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Driver:
      title: Root Type for Driver
      description: ""
      required:
      - name
      - identifier
      - dateOfBirth
      - maritalStatus
      - employmentType
      - mobileNumber
      - licence
      - cars
      type: object
      properties:
        name:
          description: Driver full name
          type: string
        identifier:
          description: Driver identifier
          type: string
        dateOfBirth:
          format: date
          description: Driver date of birth
          type: string
        maritalStatus:
          description: Driver marital status
          enum:
          - single
          - married
          - divorced
          - widowed
          type: string
        job:
          $ref: '#/components/schemas/Job'
          description: Job details
        mobileNumber:
          description: Mobile number
          type: string
        socialMedias:
          description: List of social medias with recent activities
          type: array
          items:
            $ref: '#/components/schemas/SocialMedia'
        trips:
          description: List of recent trips
          type: array
          items:
            $ref: '#/components/schemas/Trip'
        licence:
          $ref: '#/components/schemas/Licence'
          description: Driving licence details
        employmentType:
          description: Driver employment type
          enum:
          - Employed
          - Unemployed
          - PartTime
          - SelfEmployed
          - Retired
          - Student
          type: string
        cars:
          description: Driver cars
          type: array
          items:
            $ref: '#/components/schemas/Car'
      example:
        name: Felipe Rodrigues
        identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
        dateOfBirth: 2018-01-17
        maritalStatus: married
        job:
          title: Software Engineer
          startDate: 2019-03-24
          companyName: Microsoft
          companyAddress1: "South County Business Park, One Microsoft Place"
          companyAddress2: Carmanhall and Leopardstown
          companyCity: Dublin
          companyEircode: D18 P521
          companyGeoLocation: "53.2695466463407, -6.196220861370553"
        mobileNumber: +353892077323
        socialMedias:
        - socialMedia: Instagram
          url: https://www.instagram.com/felipepachecor/
          activities:
          - type: comment
            content: some text
            date: 2018-02-10T09:30Z
            url: https://www.instagram.com/felipepachecor/commentIdentfier
          - type: checkin
            content: "53.2734,-7.77832031"
            date: 2018-02-10T09:30Z
        - socialMedia: Facebook
          url: https://www.facebook.com/pachecorodriguesfelipe
          activities:
          - type: comment
            content: some text
            date: 2018-02-10T09:30Z
            url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
        trips:
        - startDate: 2018-02-10T09:30Z
          endDate: 2018-02-10T09:30Z
          distance: 6.07
          numberOfOverSpeeding: 1
          numberOfAcceleration: 2
          numberOfDeceleration: 0
          numberOfMobileUsage: 3
          riskScore: 2
          identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
          route:
            type: FeatureCollection
            features:
            - type: Feature
              properties: {}
              geometry:
                type: LineString
                coordinates:
                - - -44.91339683532715
                  - -20.145158581773966
                - - -44.92348194122314
                  - -20.1452794514767
          mobile: +353892077323
        - startDate: 2018-02-10T09:30Z
          endDate: 2018-02-10T09:30Z
          distance: 5.73
          numberOfOverSpeeding: 4
          numberOfAcceleration: 3
          numberOfDeceleration: 2
          numberOfMobileUsage: 3
          riskScore: 5
          identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
          route:
            type: FeatureCollection
            features:
            - type: Feature
              properties: {}
              geometry:
                type: LineString
                coordinates:
                - - -44.90743160247803
                  - -20.16574537177958
                - - -44.89957809448242
                  - -20.144272201095905
          mobile: +353892077323
        licence:
          type: LearnerPermit
          issueDate: 2018-01-17
          class: B
          number: ASD123FGH
          totalPenalties: 0
        employmentType: FullTime
        cars:
        - maker: Audi
          model: A4
          year: 2017
          registration: 172L1234
          value: 15000
    Job:
      title: Root Type for Job
      description: Driver job description
      required:
      - companyAddress1
      - companyCity
      - companyName
      type: object
      properties:
        title:
          description: Job title
          type: string
        startDate:
          format: date
          description: Start date of the job
          type: string
        companyName:
          description: Company name
          type: string
        companyAddress1:
          description: Company address part I
          type: string
        companyAddress2:
          description: Company address part II
          type: string
        companyCity:
          description: Company address city
          type: string
        companyEircode:
          description: Company eircode
          type: string
        companyGeoLocation:
          description: Company address latitude and longitude coordinates
          type: string
      example:
        title: Software Engineer
        startDate: 2019-03-24
        companyName: Microsoft
        companyAddress1: "South County Business Park, One Microsoft Place"
        companyAddress2: Carmanhall and Leopardstown
        companyCity: Dublin
        companyEircode: D18 P521
        companyGeoLocation: "53.2695466463407, -6.196220861370553"
    Case:
      title: Root Type for Case
      description: Potentail fraud and Policy breach case
      required:
      - comment
      - driver
      - type
      - createDate
      - probabilityScore
      type: object
      properties:
        identifier:
          description: Case identifier
          type: string
        driver:
          $ref: '#/components/schemas/Driver'
          description: Driver details
        comment:
          description: Case hint comment
          type: string
        createDate:
          format: date-time
          description: Date and time case was created
          type: string
        type:
          description: Case type
          enum:
          - alternativeDriver
          - learnerInMotorway
          - personalDetails
          type: string
        probabilityScore:
          format: float
          description: "The suspected strength of case veracity. The score is measured\
            \ between 0 and 1, whereas 0 is low confidence and 1 is high confidence"
          type: number
      example:
        identifier: A91A69AD-DE28-429B-B187-2B5AD8E083EE
        driver:
          name: Felipe Rodrigues
          identifier: B21A69AD-DE28-429B-B187-2B5AD8E083DD
          dateOfBirth: 2018-01-17
          maritalStatus: married
          job:
            title: Software Engineer
            startDate: 2019-03-24
            companyName: Microsoft
            companyAddress1: "South County Business Park, One Microsoft Place"
            companyAddress2: Carmanhall and Leopardstown
            companyCity: Dublin
            companyEircode: D18 P521
            companyGeoLocation: "53.2695466463407, -6.196220861370553"
          mobileNumber: +353892077323
          socialMedias:
          - socialMedia: Instagram
            url: https://www.instagram.com/felipepachecor/
            activities:
            - type: comment
              content: some text
              date: 2018-02-10T09:30Z
              url: https://www.instagram.com/felipepachecor/commentIdentfier
            - type: checkin
              content: "53.2734,-7.77832031"
              date: 2018-02-10T09:30Z
          - socialMedia: Facebook
            url: https://www.facebook.com/pachecorodriguesfelipe
            activities:
            - type: comment
              content: some text
              date: 2018-02-10T09:30Z
              url: https://www.facebook.com/pachecorodriguesfelipe/someactivityurl
          trips:
          - startDate: 2018-02-10T09:30Z
            endDate: 2018-02-10T09:30Z
            distance: 6.07
            numberOfOverSpeeding: 1
            numberOfAcceleration: 2
            numberOfDeceleration: 0
            numberOfMobileUsage: 3
            riskScore: 2
            identifier: 10E31288-5DD3-435B-A8F3-345C94354DBD
            route:
              type: FeatureCollection
              features:
              - type: Feature
                properties: {}
                geometry:
                  type: LineString
                  coordinates:
                  - - -44.91339683532715
                    - -20.145158581773966
                  - - -44.92348194122314
                    - -20.1452794514767
            mobile: +353892077323
          - startDate: 2018-02-10T09:30Z
            endDate: 2018-02-10T09:30Z
            distance: 5.73
            numberOfOverSpeeding: 4
            numberOfAcceleration: 3
            numberOfDeceleration: 2
            numberOfMobileUsage: 3
            riskScore: 5
            identifier: FBDD7C52-0CB2-4674-8AA2-ADFD5AD8B4E4
            route:
              type: FeatureCollection
              features:
              - type: Feature
                properties: {}
                geometry:
                  type: LineString
                  coordinates:
                  - - -44.90743160247803
                    - -20.16574537177958
                  - - -44.89957809448242
                    - -20.144272201095905
            mobile: +353892077323
          licence:
            type: LearnerPermit
            issueDate: 2018-01-17
            class: B
            number: ASD123FGH
            totalPenalties: 0
          employmentType: FullTime
          cars:
          - maker: Audi
            model: A4
            year: 2017
            registration: 172L1234
            value: 15000
        comment: "Possible driver that holds learner permit driving in motorways,\
          \ e.g. trip identfier: XXX"
        createDate: 2021-02-10T09:30Z
        type: learnerInMotorway
        probabilityScore: 0.45
    SocialMedia:
      title: Root Type for SocialMedia
      description: Social Media Details
      type: object
      properties:
        socialMedia:
          description: 'Social media name '
          enum:
          - Facebook
          - Instagram
          - Snapshat
          - Linkedin
          type: string
        url:
          description: Social media profile url
          type: string
        activities:
          description: List of recent activities
          type: array
          items:
            $ref: '#/components/schemas/Activity'
      example:
        socialMedia: Facebook
        url: https://www.facebook.com/pachecorodriguesfelipe
        activities:
        - type: checkin
          content: "52.64306343665892,-8.624267578125002"
          date: 2021-05-03 17:15
        - type: post
          content: some text
          url: https://www.facebook.com/p/CNsYpP8jsdE/
          date: 2021-05-03 17:15
    Activity:
      title: Root Type for Activity
      description: Recent activity details
      required:
      - date
      - type
      type: object
      properties:
        type:
          description: Type of activity
          enum:
          - checkin
          - post
          - comment
          type: string
        content:
          description: Content details
          type: string
        date:
          format: date-time
          description: Activity date
          type: string
        url:
          description: Activity url
          type: string
      example:
        type: checkin
        content: some text
        date: 2021-01-01 12:12
    Trip:
      title: Root Type for Trip
      description: Trips details
      required:
      - route
      - riskScore
      - numberOfOverSpeeding
      - numberOfMobileUsage
      - numberOfDeceleration
      - numberOfAcceleration
      - identifier
      - endDate
      - distance
      type: object
      properties:
        startDate:
          format: date-time
          description: 'Start date and time of trip recording '
          type: string
        endDate:
          format: date-time
          description: 'End date and time of trip recording '
          type: string
        distance:
          format: double
          description: Route distance in kilometers
          type: number
        numberOfOverSpeeding:
          format: int32
          description: Number of times that driver exceeded the road speed limit within
            the route
          type: integer
        numberOfAcceleration:
          format: int32
          description: Number of times that sudden acceleration occurred
          type: integer
        numberOfDeceleration:
          format: int32
          description: Number of times that sudden deceleration occurred
          type: integer
        numberOfMobileUsage:
          format: int32
          description: Number of times that mobile had interactions while trip recording
            app is running
          type: integer
        riskScore:
          format: int32
          description: Suggested risk score by Risk Assessor Engine based on driver
            driving habits. Min 1 and max 5. Whereas 1 is classified as excellent
            driving habits and 5 classified as very poor driving habits
          type: integer
        identifier:
          description: Trip identifier
          type: string
        route:
          description: Geojson file with route coordinates
          type: string
        mobile:
          description: Driver mobile number
          type: string
      example:
        startDate: 2018-02-10T09:30Z
        endDate: 2018-02-10T09:30Z
        distance: 7.29
        numberOfOverSpeeding: 2
        numberOfAcceleration: 1
        numberOfDeceleration: 1
        numberOfMobileUsage: 4
        riskScore: 3
        identifier: 079A3749-94C6-4611-AA95-07751277CF87
        mobile: +353892077323
        route:
          type: FeatureCollection
          features:
          - type: Feature
            properties: {}
            geometry:
              type: LineString
              coordinates:
              - - -44.90743160247803
                - -20.16574537177958
              - - -44.89957809448242
                - -20.144272201095905
              - - -44.90734577178955
                - -20.141895064444356
              - - -44.90906238555908
                - -20.14664930157007
              - - -44.9100923538208
                - -20.146246405731016
              - - -44.910264015197754
                - -20.145440610934813
              - - -44.912796020507805
                - -20.144433361593336
              - - -44.91339683532715
                - -20.145158581773966
              - - -44.92348194122314
                - -20.1452794514767
    Licence:
      title: Root Type for Licence
      description: Driving licence details
      required:
      - class
      - issueDate
      - number
      - type
      type: object
      properties:
        type:
          description: Driving licence type. Full or learner permit
          enum:
          - FullPermit
          - LearnerPermit
          type: string
        issueDate:
          format: date
          description: Driving licence issue date
          type: string
        class:
          description: "Licence class. A- motorbikes, B- cars, C- vans, D- trucks"
          enum:
          - A
          - B
          - C
          - D
          - E
          type: string
        number:
          description: Driving licence number
          type: string
        totalPenalties:
          description: Current total penalties
          type: integer
      example:
        type: FullPermit
        issueDate: 2018-01-17
        class: D
        number: 123ABC321
        totalPenalties: 0
    Car:
      title: Root Type for Car
      description: Car details
      required:
      - maker
      - model
      - registration
      - year
      type: object
      properties:
        maker:
          description: Car maker
          type: string
        model:
          description: Car model
          type: string
        year:
          format: int32
          description: Car manufacturing year
          type: integer
        registration:
          description: Car registration plate
          type: string
        value:
          format: double
          description: Car estimated value
          type: number
      example:
        maker: Audi
        model: A4
        year: 2017
        registration: 172L1234
        value: 15000.23
