---
openapi: 3.0.2
info:
  title: Policy Management
  version: 1.0.0
  description: 'API to manage driver risks '
  termsOfService: http://swagger.io/terms/
  contact:
    name: Peregrine Software Architecture Team
    url: https://peregrine.com
    email: software.architecture@peregrine.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://dev.peregrine.com/api
  description: Development server for APIs test
- url: http://peregrine.com/api
  description: Production APIs server
paths:
  /drivers:
    summary: Drivers management
    description: Retrieve and create list of drivers
    get:
      parameters:
      - examples:
          single county:
            value: '"Limerick"'
          multiple counties:
            value: "\"Dublin, Limerick\""
        name: county
        description: Filter drivers by home county
        schema:
          type: string
        in: query
      - examples:
          end date:
            value: '"2000-01-17"'
        name: dobEnd
        description: 'Filter drivers by end of birthdate  '
        schema:
          format: date
          type: string
        in: query
      - examples:
          end date:
            value: '"2000-01-17"'
        name: dobStart
        description: Filter drivers from start of birthdate
        schema:
          format: date
          type: string
        in: query
      - examples:
          single gender:
            value: '"female"'
          multiple genders:
            value: "\"male, female\""
        name: gender
        description: Filter drivers by gender
        schema:
          enum:
          - male
          - female
          type: string
        in: query
      - examples:
          single class:
            value: '"A"'
          multiple class:
            value: "\"B, E\""
        name: licenceClass
        description: Filter driver by licence class
        schema:
          enum:
          - A
          - B
          - C
          - D
          - E
          type: string
        in: query
      - examples:
          end date:
            value: '"2017-02-27"'
        name: licenceIssueDateEnd
        description: "Filter drivers by licence issue date, issue date up to date\
          \ parameter value. "
        schema:
          format: date
          type: string
        in: query
      - examples:
          start date:
            value: '"2018-11-17"'
        name: licenceIssueDateStart
        description: "Filter drivers by licence issue date, issue date from the date\
          \ parameter value. "
        schema:
          format: date
          type: string
        in: query
      - examples:
          licence type:
            value: '"fullPermit"'
        name: licenceType
        description: Licence type. Full or learner permit
        schema:
          enum:
          - fullPermit
          - learnerPermit
          type: string
        in: query
      - examples:
          skip:
            value: "22"
        name: skip
        description: Offset in the driver records list
        schema:
          type: integer
        in: query
      - examples:
          top:
            value: "63"
        name: top
        description: 'Restrict number of drivers in a list. Min 1 and max 100. Default
          is set to max '
        schema:
          type: integer
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'
          description: Success operation
      summary: Get drivers
      description: Retrieve and filter list of drivers
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Driver'
            examples:
              list of drivers:
                value:
                - identifier: ""
                  name: Paul O'Conell
                  address1: 45 Mew Road
                  address2: Annacotty
                  county: Limerick
                  licence:
                    type: IrishLearning
                    issueDate: 2010-01-17
                    class: A
                    number: :LGKHD987
                  gender: male
                  dateOfBirth: 2018-01-17
                  cars:
                  - maker: Audi
                    model: A6
                    year: 2020
                    registration: 202LASD
                    value: 37580.5
                  proposedRisk: Low
                  eircode: V9087A5
        required: true
      responses:
        "201":
          description: Success operation
        "400":
          description: Invalid body payload
      summary: Create new drivers
      description: Create drivers based on payload received in the body request
  /drivers/{identifier}:
    summary: Single driver management
    description: "Update, read and delete driver details"
    get:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
              examples:
                driver details:
                  value:
                    identifier: ""
                    name: Paul O'Conell
                    address1: 45 Mew Road
                    address2: Annacotty
                    county: Limerick
                    licence:
                      type: IrishLearning
                      issueDate: 2010-01-17
                      class: A
                      number: :LGKHD987
                    gender: male
                    dateOfBirth: 2018-01-17
                    cars:
                    - maker: Audi
                      model: A6
                      year: 2020
                      registration: 202LASD
                      value: 37580.5
                    proposedRisk: Low
                    eircode: V9087A5
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Driver not found
      summary: Get single driver
      description: Rretrieve single driver details
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Driver'
            examples:
              driver with existing identifier:
                value:
                  identifier: B1530C2C-B405-41D4-B842-A3338B0EA338
                  name: Paul O'Conell
                  address1: 45 Mew Road
                  address2: Annacotty
                  county: Limerick
                  licence:
                    type: IrishLearning
                    issueDate: 2010-01-17
                    class: A
                    number: :LGKHD987
                  gender: male
                  dateOfBirth: 2018-01-17
                  cars:
                  - maker: Audi
                    model: A6
                    year: 2020
                    registration: 202LASD
                    value: 37580.5
                  proposedRisk: Low
                  eircode: V9087A5
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: "Invalid body payload, Invalid parameter"
        "404":
          description: Driver not found
      summary: Update single driver
      description: Update single driver details
    delete:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "204":
          description: 'Success operation '
        "401":
          description: User not authorized
        "404":
          description: Driver not found
        "400":
          description: "Invalid Id, Invalid body payload"
      summary: Delete single driver
      description: Delete single driver details
    parameters:
    - examples:
        identifier:
          value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
      name: identifier
      description: Driver identifier
      schema:
        type: string
      in: path
      required: true
  /drivers/{identifier}/accidents:
    summary: Accidents management
    description: "Update, read and create driver accident details"
    get:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          'date ':
            value: '"2018-02-10T09:30Z"'
        name: endDate
        description: Filter driver accidents to a parameter value date
        schema:
          format: date-time
          type: string
        in: query
      - examples:
          date:
            value: '"2018-02-10T09:30Z"'
        name: startDate
        description: Filter driver accidents from parameter value date
        schema:
          format: date-time
          type: string
        in: query
      - examples:
          user claimed corverage:
            value: "true"
        name: hasClaimed
        description: Indicates if driver activated the policy to claim accident coverage
        schema:
          type: boolean
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accident'
              examples:
                list of accidents:
                  value:
                  - date: 2018-02-10T09:30Z
                    carPlate: 172L1234
                    thirdPartyCarPlates:
                    - 132L1234
                    - 152L1234
                    claimedValue: 0
                    hasClaimed: false
                    identifier: 38BEE204-DD32-4CA9-8961-C1C857065665
                    address: "Tipperary Road, Limerick city, Co. Limercik"
                  - date: 2021-02-10T09:30Z
                    carPlate: 172L1234
                    claimedValue: 4500.65
                    hasClaimed: true
                    identifier: 78BEE204-DD32-4CA9-8961-C1C857076776
                    address: "Henry Street, Limerick city, Co. Limercik"
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Driver not found
      summary: Get driver accidents
      description: Rretrieve single driver accidents details
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Accident'
            examples:
              accident detail:
                value:
                  date: 2018-02-10T09:30Z
                  carPlate: 172L1234
                  thirdPartyCarPlates:
                  - 132L1234
                  - 152L1234
                  claimedValue: 0
                  hasClaimed: false
                  identifier: 38BEE204-DD32-4CA9-8961-C1C857065665
                  address: "Tipperary Road, Limerick city, Co. Limercik"
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          accident identifier:
            value: '"38BEE204-DD32-4CA9-8961-C1C857065665"'
        name: accidentIdentifier
        description: Identifier of the accident
        schema:
          type: string
        in: query
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: "Invalid body payload, Invalid parameter"
        "404":
          description: Accident not found
      summary: Update driver accident
      description: Update single accident details
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Accident'
            examples:
              list of accidents:
                value:
                - date: 2018-02-10T09:30Z
                  carPlate: 172L1234
                  thirdPartyCarPlates:
                  - 132L1234
                  - 152L1234
                  claimedValue: 0
                  hasClaimed: false
                  address: "Tipperary Road, Limerick city, Co. Limercik"
                - date: 2021-02-10T09:30Z
                  carPlate: 172L1234
                  claimedValue: 4500.65
                  hasClaimed: true
                  address: "Henry Street, Limerick city, Co. Limercik"
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "201":
          description: Success operation
        "400":
          description: "Invalid indentifier, Invalid body payload"
        "404":
          description: Driver not found
      summary: Create new accidents
      description: Create new accident details
    parameters:
    - examples:
        identifier:
          value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
      name: identifier
      description: Driver identifier
      schema:
        type: string
      in: path
      required: true
  /drivers/{identifier}/penalties:
    summary: Licence penalties management
    description: "Create, update, read and delete licence penalty details"
    get:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          'date ':
            value: '"2018-02-10T09:30Z"'
        name: endDate
        description: Filter licence penalties to the parameter value date
        schema:
          format: date
          type: string
        in: query
      - examples:
          date:
            value: '"2018-02-10T09:30Z"'
        name: startDate
        description: Filter licence penalties from the parameter value date
        schema:
          format: date
          type: string
        in: query
      - examples:
          single penalty:
            value: '"overtaking"'
          multiple penalties:
            value: "\"overtaking, speeding\""
        name: type
        description: Type of penalty
        schema:
          enum:
          - speeding
          - overtaking
          - mobile
          - parking
          type: string
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Penalty'
              examples:
                list of penalties:
                  value:
                  - date: 2018-02-10T09:30Z
                    type: speeding
                    points: 3
                    address: "William Street, Limerick city"
                    county: Limerick
                    carPlate: 152L1234
                    identifier: 38BEE204-DD32-4CA9-8961-C1C857065665
                  - date: 2018-02-10T09:30Z
                    type: parking
                    points: 2
                    address: "O'Connel Street, Limerick City"
                    county: Limercik
                    carPlate: 152L1234
                    identifier: 78BEE204-DD32-4CA9-8961-C1C857076776
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Penalties not found
      summary: Get driving licence penalties
      description: Rretrieve driver licence penalties details
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Penalty'
            examples:
              penalty:
                value:
                  date: 2018-02-10T09:30Z
                  type: speeding
                  points: 3
                  address: "William Street, Limerick city"
                  county: Limerick
                  carPlate: 152L1234
                  identifier: 38BEE204-DD32-4CA9-8961-C1C857065665
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          penalty identifier:
            value: '"B1530C2C-B405-41D4-B842-A3338B0EA338"'
        name: penaltyIdentifier
        description: Identifier of the penalty
        schema:
          type: string
        in: query
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: "Invalid body payload, Invalid parameter"
        "404":
          description: Penalty not found
      summary: Update driving licence penalty
      description: Update single licence penalty details
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Penalty'
            examples:
              list of penalties:
                value:
                - date: 2018-02-10T09:30Z
                  type: speeding
                  points: 3
                  address: "William Street, Limerick city"
                  county: Limerick
                  carPlate: 152L1234
                - date: 2018-02-10T09:30Z
                  type: parking
                  points: 2
                  address: "O'Connel Street, Limerick City"
                  county: Limercik
                  carPlate: 152L1234
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "201":
          description: Success operation
        "400":
          description: "Invalid indentifier, Invalid body payload"
        "404":
          description: Driver not found
      summary: Create driving licence penalties
      description: Create new list of penalties details
    delete:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          penalty identifier:
            value: '"D27CF3CB-BA42-4A42-B140-8287BF2BA821"'
        name: penaltyIdentifier
        description: Identifier of the penalty
        schema:
          type: string
        in: query
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: 'Invalid parameter '
        "404":
          description: Penalty not found
        "401":
          description: Unauthorized resource
      summary: Delete driving licence penalty
      description: Delete licence penalties
    parameters:
    - examples:
        identifier:
          value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
      name: identifier
      description: Driver identifier
      schema:
        type: string
      in: path
      required: true
  /drivers/{identifier}/trips:
    summary: Trips management
    description: "Create, update, read and delete driver trips details"
    get:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          'date ':
            value: '"2018-02-10T09:30Z"'
        name: endDate
        description: Filter driver trips to the parameter value date
        schema:
          format: date
          type: string
        in: query
      - examples:
          date:
            value: '"2018-02-10T09:30Z"'
        name: startDate
        description: Filter driver trips from the parameter value date
        schema:
          format: date
          type: string
        in: query
      - examples:
          single score:
            value: '"1"'
          multiple scores:
            value: "\"3,4,5\""
        name: riskScore
        description: Driver risk score proposed by Risk Assessor Engine
        schema:
          enum:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          type: string
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
              examples:
                list of trips:
                  value:
                  - startDate: 2021-02-10T09:30Z
                    endDate: 2021-02-10T09:50Z
                    distance: 10.4
                    numberOfOverSpeeding: 0
                    numberOfAcceleration: 0
                    numberOfDeceleration: 0
                    numberOfMobileUsage: 2
                    riskScore: 1
                    identifier: 54BAE4ED-15C7-493A-BED6-D4D0DFFCD492
                  - startDate: 2021-02-11T09:30Z
                    endDate: 2021-02-11T10:10Z
                    distance: 50
                    numberOfOverSpeeding: 3
                    numberOfAcceleration: 2
                    numberOfDeceleration: 1
                    numberOfMobileUsage: 2
                    riskScore: 4
                    identifier: D27CF3CB-BA42-4A42-B140-8287BF2BA821
          description: Success operation
        "400":
          description: Invalid parameter
        "404":
          description: Trips not found
      summary: Get driver trips
      description: Rretrieve driver trips details
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
            examples:
              trip payload:
                value:
                  startDate: 2021-02-10T09:30Z
                  endDate: 2021-02-10T09:40Z
                  distance: 5.05
                  numberOfOverSpeeding: 0
                  numberOfAcceleration: 0
                  numberOfDeceleration: 0
                  numberOfMobileUsage: 0
                  riskScore: 1
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Trip identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          penalty identifier:
            value: '"B1530C2C-B405-41D4-B842-A3338B0EA338"'
        name: tripIdentifier
        description: 'Identifier of the trip  '
        schema:
          type: string
        in: query
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: "Invalid body payload, Invalid parameter"
        "404":
          description: Trip not found
      summary: Update driver trip
      description: Update single driver trip details
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Trip'
            examples:
              list of trips:
                value:
                - startDate: 2021-02-10T09:30Z
                  endDate: 2021-02-10T09:40Z
                  distance: 10.15
                  numberOfOverSpeeding: 2
                  numberOfAcceleration: 2
                  numberOfDeceleration: 1
                  numberOfMobileUsage: 1
                  riskScore: 3
                - startDate: 2021-04-10T17:30Z
                  endDate: 2021-04-10T17:55Z
                  distance: 20.34
                  numberOfOverSpeeding: 0
                  numberOfAcceleration: 0
                  numberOfDeceleration: 0
                  numberOfMobileUsage: 0
                  riskScore: 1
        required: true
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "201":
          description: Success operation
        "400":
          description: "Invalid indentifier, Invalid body payload"
        "404":
          description: Driver not found
      summary: Create driver trip
      description: 'Create new list of driver trips     '
    delete:
      parameters:
      - examples:
          identifier:
            value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
        name: identifier
        description: Driver identifier
        schema:
          type: string
        in: path
        required: true
      - examples:
          trip identifier:
            value: '"D27CF3CB-BA42-4A42-B140-8287BF2BA821"'
        name: tripIdentifier
        description: Identifier of the trip
        schema:
          type: string
        in: query
        required: true
      responses:
        "204":
          description: Success operation
        "400":
          description: 'Invalid parameter '
        "401":
          description: Unauthorized resource
        "404":
          description: Trip not found
      summary: Delete driver trip
      description: Delete driver trips
    parameters:
    - examples:
        identifier:
          value: '"654EF6C5-4F8C-4AAE-A9E1-7914BD1D8658"'
      name: identifier
      description: Driver identifier
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Accident:
      title: Root Type for Accident
      description: Accident Details
      required:
      - carPlate
      - date
      - address
      type: object
      properties:
        date:
          format: date-time
          description: Accident date
          type: string
        carPlate:
          description: Car registration plate
          type: string
        thirdPartyCarPlates:
          description: "List of registration plate of third party cars involved in\
            \ the accident, if any."
          type: array
          items:
            type: string
        claimedValue:
          format: double
          description: Total value claimed
          type: number
        hasClaimed:
          description: Indicates wheter insurance claim was activated for this accident
          type: boolean
        identifier:
          description: Accident identifier
          type: string
        address:
          description: Accident address
          type: string
      example:
        date: 2020-01-25T23:10Z
        carPlate: 172L1234
        thirdPartyCarPlates:
        - 152L3421
        - 162L1267
        claimedValue: 35000
        hasClaimed: true
        identifier: 38BEE204-DD32-4CA9-8961-C1C857065665
        address: "Dublin Road, Limerick City, Co. Limerick"
    Driver:
      title: Root Type for Driver
      description: Driver Details
      required:
      - address1
      - cars
      - county
      - licence
      - name
      - dateOfBirth
      type: object
      properties:
        identifier:
          description: Driver unique identifier
          type: string
        name:
          description: Driver full name
          type: string
        address1:
          description: Driver address part I
          type: string
        address2:
          description: Driver address part II
          type: string
        county:
          description: Driver county address
          type: string
        licence:
          $ref: '#/components/schemas/Licence'
          description: Licence details
          properties:
            type:
              type: string
            issueDate:
              format: date
              type: string
            classification:
              type: string
            number:
              type: string
        gender:
          description: Driver gender
          enum:
          - male
          - female
          type: string
        dateOfBirth:
          format: date
          description: Driver date of birth
          type: string
        cars:
          description: Driver cars list
          type: array
          items:
            $ref: '#/components/schemas/Car'
        proposedRisk:
          description: "Propose risk score provided by the Risk Assessor Engine. There\
            \ are five levels of score, they are Low, MediumLow, Medium, MediumHigh\
            \ and High"
          enum:
          - Low
          - MediumLow
          - Medium
          - MediumHigh
          - High
          type: string
        eircode:
          description: Driver home eircode
          type: string
      example:
        identifier: B1530C2C-B405-41D4-B842-A3338B0EA338
        name: Felipe Rodrigues
        address1: 25 Castlerock Road
        address2: Castleconnell
        county: Limerick
        licence:
          type: FullIrish
          issueDate: 2018-01-17
          class: B
          number: 1234567ABC
        gender: male
        dateOfBirth: 2018-01-17
        cars:
        - maker: Audi
          model: A7
          year: 2017
          registration: 172L1234
          value: 15000
        proposedRisk: High
    Car:
      title: Root Type for Car
      description: Car details
      required:
      - maker
      - model
      - registration
      - year
      type: object
      properties:
        maker:
          description: Car maker
          type: string
        model:
          description: Car model
          type: string
        year:
          format: int32
          description: Car manufacturing year
          type: integer
        registration:
          description: Car registration plate
          type: string
        value:
          format: double
          description: Car estimated value
          type: number
      example:
        maker: Audi
        model: A4
        year: 2017
        registration: 172L1234
        value: 15000
    Licence:
      title: Root Type for Licence
      description: Driver licence details
      required:
      - class
      - type
      - number
      type: object
      properties:
        type:
          description: Licence type. Full or learner permit
          type: string
        issueDate:
          format: date
          description: Licence issue date
          type: string
        class:
          description: "Licence class. A- motorbikes, B- cars, C- vans, D- trucks"
          enum:
          - A
          - B
          - C
          - D
          - E
          type: string
        number:
          description: Licence number
          type: string
      example:
        type: FullPermit
        issueDate: 2018-01-17
        class: D
        number: 123ABC321
    Penalty:
      title: Root Type for Penalty
      description: Licence penalty points details
      required:
      - carPlate
      - county
      - date
      - type
      - points
      - address
      type: object
      properties:
        date:
          format: date-time
          description: Penalty date and time
          type: string
        type:
          description: Penalty type
          enum:
          - speeding
          - overtaking
          - parking
          - mobile
          type: string
        points:
          format: int32
          description: Penalty points
          type: integer
        address:
          description: Address where the penalty occurred
          type: string
        county:
          description: County address where the penalty occurred
          type: string
        carPlate:
          description: Car registration plate
          type: string
        identifier:
          description: Penalty identifier
          type: string
      example:
        identifier: 8F347DA9-1E28-44CE-8F7B-3292ADF51589
        date: 2018-02-10T09:30Z
        type: speeding
        points: 2
        address: "Dublin Road, Limerick City"
        county: Limerick
        carPlate: 172L1234
    Trip:
      title: Root Type for Trip
      description: Trip details recorded by trip recorder app
      required:
      - distance
      - startDate
      - numberOfAcceleration
      - numberOfDeceleration
      - endDate
      - numberOfMobileUsage
      - numberOfOverSpeeding
      type: object
      properties:
        startDate:
          format: date-time
          description: 'Start date and time of trip recording '
          type: string
        endDate:
          format: date-time
          description: 'End date and time of trip recording '
          type: string
        distance:
          format: double
          description: Route distance in kilometers
          type: number
        numberOfOverSpeeding:
          format: int32
          description: Number of times that driver exceeded the road speed limit within
            the route
          type: integer
        numberOfAcceleration:
          format: int32
          description: Number of times that sudden acceleration occurred
          type: integer
        numberOfDeceleration:
          format: int32
          description: Number of times that sudden deceleration occurred
          type: integer
        numberOfMobileUsage:
          format: int32
          description: Number of times that mobile had interactions while trip recording
            app is running
          type: integer
        riskScore:
          description: Suggested risk score by Risk Assessor Engine based on driver
            driving habits. Min 1 and max 5. Whereas 1 is classified as excellent
            driving habits and 5 classified as very poor driving habits
          type: integer
        identifier:
          description: Trip identifier
          type: string
      example:
        startDate: 2018-02-10T09:30Z
        endDate: 2018-02-10T09:30Z
        distance: 40.29
        numberOfOverSpeeding: 2
        numberOfAcceleration: 1
        numberOfDeceleration: 1
        numberOfMobileUsage: 4
        riskScore: 3
        identifier: 079A3749-94C6-4611-AA95-07751277CF87
